### ISSUE TITLE
UniformWarning(Inactive) is not ignored

### ISSUE THREAD

**Issue by BrandonDyer64** [phaazon/luminance-rs#242] opened 2019-10-29 02:47 UTC
In this code

```rust
let program = Program::<(), (), ShaderInterface>::from_strings(None, VS, None, FS)
    .expect("program creation")
    .ignore_warnings();
```

the program is unwrapped before `ignore_warnings` is called.

This means that if I have an unused uniform, I get a panic.

**Comment by phaazon** [comment] 2019-10-29 14:34
So, the first `expect` / `unwrap` _should_ be there in case the program fails to link or compile, for instance. The inactive uniforms can also generate such errors in case you haven’t explicitly ask to ignore them.

Can you show me how you declare `ShaderInterface`?

**Comment by phaazon** [comment] 2019-10-29 14:38
To complement my comment, this is not a bug, but maybe the documentation of that function should be reworked so that people don’t get confused about how all of this works.

**Comment by BrandonDyer64** [comment] 2019-10-29 16:31
My `ShaderInterface` just looked something like this:
```rust
#[derive(UniformInterface)]
struct ShaderInterface {
  time: Uniform<f32>,
}
```
I've recently switched to using the method of querying uniforms (`iface.query()`), but it seems strange to need to run these queries every frame.

**Comment by phaazon** [comment] 2019-10-30 16:00
Your `ShaderInterface::time` is needed to be active with that current definition. Annotate it with `#[uniform(unbound)]` to authorize ignoring it. :) The misunderstanding is on the `ignore_warnings` method. That function ignore _warnings_ but in your case, it’s a hard error.

**Comment by phaazon** [comment] 2019-11-01 01:27
luminance could go the regular compiler way and “don’t care”, but since we have the possibility to query that information, it can provide useful hints and prevent possible bugs. :)

**Comment by BrandonDyer64** [comment] 2019-11-01 01:37
Oh yeah, I'm all in for making these warnings known, but debugging becomes really difficult when you _need_ to use every uniform, and you don't want to have to rewrite your code when you're done.

**Comment by phaazon** [comment] 2020-07-25 14:46
Closing because this is the expected behavior.

- Creating a shader program is fallible (compilation error, link error, etc.). Non-unbound uniform (in the shader interface) will also trigger an error here. The error value will be set to a warning type, yet it’s still considered an error.
- Unbound uniforms won’t generate hard errors (so you’ll get an `Ok(_)` value), but the returned value can still inspect the warnings. `ignore_warnings` will simply return the `Program` by moving out of the `BuiltProgram`.

**Closed by phaazon** 2020-07-25 14:46 UTC
Labels: easy, enhancement
